#!/usr/bin/env python3
"""Generate CMake and C configuration from a project .config (issue #63).

Reads the SDK Kconfig tree plus the project-local ``.config`` and emits into
``--out-dir``:

* ``config.cmake``      -- ``set(CONFIG_<SYM> <value>)`` for every defined
  symbol; included by ``sdk/cmake/kconfig.cmake`` which maps the CONFIG_*
  values onto the legacy variable names used across the SDK CMake tree.
* ``stm32_autoconf.h``  -- standard Kconfig autoconf header consumed by
  ``FreeRTOSConfig.h`` (and any future C/C++ user).

The script is strict: any kconfiglib warning (unknown symbol, assignment
ignored because of unsatisfied dependencies, out-of-range value) is a hard
error, so a hand-edited ``.config`` cannot silently drift from the tree.
"""

import argparse
import os
import sys
from pathlib import Path

import kconfiglib

_CMAKE_HEADER = """\
# Generated by stm32-sdk genconfig.py -- do not edit.
# Source of truth: the project-local .config file.
"""


def _cmake_value(sym: kconfiglib.Symbol) -> str | None:
    """Render a symbol's value for config.cmake, or None to skip it."""
    if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
        return "ON" if sym.tri_value == 2 else "OFF"
    if sym.type in (kconfiglib.INT, kconfiglib.HEX):
        return sym.str_value if sym.str_value else None
    if sym.type == kconfiglib.STRING:
        return f'"{sym.str_value}"'
    return None


def _rejected_assignments(kconf: kconfiglib.Kconfig) -> list[str]:
    """Assignments from .config that evaluation did not honour.

    kconfiglib silently drops assignments whose dependencies are unsatisfied
    or whose value falls outside the declared range; compare what the user
    wrote against what the tree evaluated to (the Zephyr approach) so a
    hand-edited .config cannot drift silently.
    """
    errors: list[str] = []
    for sym in kconf.unique_defined_syms:
        if sym.user_value is None:
            continue
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            if sym.user_value != sym.tri_value:
                requested = kconfiglib.TRI_TO_STR[sym.user_value]
                actual = kconfiglib.TRI_TO_STR[sym.tri_value]
                errors.append(
                    f"{sym.name} was assigned '{requested}' but evaluated to "
                    f"'{actual}' (unsatisfied dependencies?)"
                )
        elif str(sym.user_value) != sym.str_value:
            errors.append(
                f"{sym.name} was assigned '{sym.user_value}' but evaluated "
                f"to '{sym.str_value}' (out of range?)"
            )
    return errors


def _cross_checks(kconf: kconfiglib.Kconfig) -> list[str]:
    """Constraints Kconfig ranges cannot express (strict inequalities)."""
    errors: list[str] = []
    freertos = kconf.syms.get("STM32_USE_FREERTOS")
    if freertos is not None and freertos.tri_value == 2:
        timer_prio = int(kconf.syms["FREERTOS_TIMER_TASK_PRIORITY"].str_value)
        max_prio = int(kconf.syms["FREERTOS_MAX_PRIORITIES"].str_value)
        if timer_prio >= max_prio:
            errors.append(
                f"FREERTOS_TIMER_TASK_PRIORITY={timer_prio} must be strictly "
                f"below FREERTOS_MAX_PRIORITIES={max_prio}"
            )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate config.cmake + stm32_autoconf.h from .config"
    )
    parser.add_argument("--kconfig", required=True, help="Path to sdk/Kconfig")
    parser.add_argument("--dotconfig", required=True, help="Project .config")
    parser.add_argument("--out-dir", required=True, help="Output directory")
    args = parser.parse_args()

    kconfig_root = Path(args.kconfig).resolve()
    dotconfig = Path(args.dotconfig)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if not dotconfig.is_file():
        print(f"genconfig: .config not found: {dotconfig}", file=sys.stderr)
        return 2

    # source paths inside the tree are relative to the SDK root
    os.environ["srctree"] = str(kconfig_root.parent)
    os.environ.setdefault(
        "STM32_KCONFIG_CHIP_FRAGMENT", str(out_dir / "Kconfig.chip")
    )

    kconf = kconfiglib.Kconfig(str(kconfig_root), warn_to_stderr=False)
    kconf.warn_assign_undef = True
    kconf.warn_assign_override = True
    kconf.warn_assign_redun = False
    kconf.load_config(str(dotconfig))

    problems = (
        list(kconf.warnings)
        + _rejected_assignments(kconf)
        + _cross_checks(kconf)
    )
    if problems:
        print(f"genconfig: invalid {dotconfig}:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(
            "genconfig: fix the file by hand or run `stmtool config`",
            file=sys.stderr,
        )
        return 1

    kconf.write_autoconf(
        str(out_dir / "stm32_autoconf.h"),
        header="/* Generated by stm32-sdk genconfig.py -- do not edit. */\n",
    )

    lines = [_CMAKE_HEADER]
    for sym in kconf.unique_defined_syms:
        value = _cmake_value(sym)
        if value is not None:
            lines.append(f"set(CONFIG_{sym.name} {value})")
    (out_dir / "config.cmake").write_text("\n".join(lines) + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
