# Kconfig processing (#63, v0.2.2). The project-local .config is the single
# source of truth for firmware content; genconfig.py turns it into
# config.cmake (included here) and stm32_autoconf.h (consumed by
# FreeRTOSConfig.h). Included by stm32_sdk.cmake after the STM32_CHIP check
# and before family resolution, because the float ABI comes from .config.

set(STM32_DOTCONFIG "${CMAKE_SOURCE_DIR}/.config")
set(STM32_GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")

if(NOT EXISTS ${STM32_DOTCONFIG})
    message(FATAL_ERROR
        "No .config found at ${STM32_DOTCONFIG}.\n"
        "Since SDK v0.2.2 firmware configuration lives in a Kconfig .config "
        "file (the old -DSTM32_USE_*/set() path was removed). Create one:\n"
        "  - run `stmtool config` (interactive menuconfig), or\n"
        "  - copy a template defconfig: "
        "`cp <sdk>/templates/<category>/<template>/defconfig .config`\n"
        "Migration guide: docs/migration.md#new-in-v022")
endif()

file(MAKE_DIRECTORY ${STM32_GENERATED_DIR})

# Chip fragment: family facts derived from STM32_CHIP, injected into the tree
# via the STM32_KCONFIG_CHIP_FRAGMENT osource. Only the family bool, the chip
# name and the core capabilities for now; per-chip sizes join with the
# partition layer (#62).
string(SUBSTRING "${STM32_CHIP}" 5 2 _stm32_family_letters)
string(TOLOWER "stm32${_stm32_family_letters}" _stm32_kconfig_family)
string(TOUPPER "${_stm32_kconfig_family}" _stm32_kconfig_family_upper)

# ITM / SWO belongs to the ARMv7-M debug block: core_cm0plus.h does not
# declare ITM_Type or ITM_SendChar at all, so on a Cortex-M0/M0+ part the ITM
# log backend cannot even compile. Gate it in Kconfig instead, so an
# unbuildable combination is rejected at configure time with a readable
# message (#98). Derived from the chip name rather than from the family file
# because this runs before stm32_families.cmake -- the float ABI has to come
# out of .config before STM32_ARCH_FLAGS can be built.
set(_stm32_cortex_m0_families stm32f0 stm32g0 stm32l0)
if(_stm32_kconfig_family IN_LIST _stm32_cortex_m0_families)
    set(_stm32_has_itm "n")
else()
    set(_stm32_has_itm "y")
endif()

file(WRITE ${STM32_GENERATED_DIR}/Kconfig.chip
    "# Generated by kconfig.cmake from STM32_CHIP=${STM32_CHIP} -- do not edit.\n"
    "config STM32_FAMILY_${_stm32_kconfig_family_upper}\n"
    "\tdef_bool y\n"
    "\n"
    "config STM32_CHIP_NAME\n"
    "\tstring\n"
    "\tdefault \"${STM32_CHIP}\"\n"
    "\n"
    "config STM32_CORE_HAS_ITM\n"
    "\tdef_bool ${_stm32_has_itm}\n")

find_package(Python3 COMPONENTS Interpreter REQUIRED)

execute_process(
    COMMAND ${CMAKE_COMMAND} -E env
        STM32_KCONFIG_CHIP_FRAGMENT=${STM32_GENERATED_DIR}/Kconfig.chip
        ${Python3_EXECUTABLE} ${_STM32_SDK_DIR}/scripts/kconfig/genconfig.py
        --kconfig ${_STM32_SDK_DIR}/Kconfig
        --dotconfig ${STM32_DOTCONFIG}
        --out-dir ${STM32_GENERATED_DIR}
    RESULT_VARIABLE _stm32_genconfig_rc
    OUTPUT_VARIABLE _stm32_genconfig_out
    ERROR_VARIABLE _stm32_genconfig_err
)

if(NOT _stm32_genconfig_rc EQUAL 0)
    message(FATAL_ERROR
        "Kconfig generation failed:\n"
        "${_stm32_genconfig_out}${_stm32_genconfig_err}")
endif()

include(${STM32_GENERATED_DIR}/config.cmake)

# Re-run configure whenever the configuration or the tree changes.
file(GLOB _stm32_kconfig_fragments ${_STM32_SDK_DIR}/*/Kconfig)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${STM32_DOTCONFIG}
    ${_STM32_SDK_DIR}/Kconfig
    ${_stm32_kconfig_fragments}
    ${_STM32_SDK_DIR}/scripts/kconfig/genconfig.py
)

# Map CONFIG_* onto the variable names the rest of the SDK CMake tree uses.
set(STM32_USE_FREERTOS ${CONFIG_STM32_USE_FREERTOS})
set(STM32_USE_DRIVERS ${CONFIG_STM32_USE_DRIVERS})
set(STM32_USE_SENSORS ${CONFIG_STM32_USE_SENSORS})
set(STM32_USE_STORAGE ${CONFIG_STM32_USE_STORAGE})
set(STM32_USE_SYSTEM ${CONFIG_STM32_USE_SYSTEM})
set(STM32_USE_TESTING ${CONFIG_STM32_USE_TESTING})
set(STM32_HSE_VALUE ${CONFIG_STM32_HSE_VALUE})

if(CONFIG_STM32_FLOAT_ABI_SOFTFP)
    set(STM32_FLOAT_ABI "softfp")
elseif(CONFIG_STM32_FLOAT_ABI_SOFT)
    set(STM32_FLOAT_ABI "soft")
else()
    set(STM32_FLOAT_ABI "hard")
endif()

if(STM32_USE_DRIVERS)
    set(STM32_LOG_LEVEL_NUM ${CONFIG_STM32_LOG_LEVEL_NUM})
    set(STM32_LOG_BACKEND_NUM ${CONFIG_STM32_LOG_BACKEND_NUM})
endif()
